application: kindycal
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: kindycal.application

- url: /favicon\.ico$
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /login.html$
  script: kindycal.application

- url: /admin_login.html$
  script: kindycal.application

- url: /staff_login.html$
  script: kindycal.application

- url: /index.html$
  script: kindycal.application

- url: /staff.html$
  script: kindycal.application

- url: /admin.html$
  script: kindycal.application

- url: /edit_terms.html$
  script: kindycal.application

- url: /edit_groups.html$
  script: kindycal.application

- url: /events.html$
  script: kindycal.application

- url: /(..*\.html)$
  static_files: \1
  upload: ..*\.html
  application_readable: true

- url: /(..*\.css)$
  static_files: \1
  upload: ..*\.css

- url: /(..*\.js)$
  static_files: \1
  upload: ..*\.js

- url: /..*
  script: kindycal.application

- url: /script/.*
  script: kindycal.application

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?jquery-ui[^/]*/tests/.*$
- ^(.*/)?jquery-ui[^/]*/demos/.*$
