application: bckindycal-1197
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: kindycal.application

- url: /jquery-ui-1.11
  static_dir: jquery-ui-1.11
  
- url: /favicon\.ico$
  static_files: favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /fair_images
  static_dir: fair_images

- url: /fair_css
  static_dir: fair_css

- url: /fair_fonts
  static_dir: fair_fonts

- url: /tinymce
  static_dir: tinymce
  
- url: /login.html$
  script: kindycal.application

- url: /admin_login.html$
  script: kindycal.application

- url: /change_parent_password.html
  script: kindycal.application

- url: /change_staff_password.html
  script: kindycal.application

- url: /staff_login.html$
  script: kindycal.application

- url: /index.html$
  script: kindycal.application

- url: /staff.html$
  script: kindycal.application

- url: /admin.html$
  script: kindycal.application

- url: /edit_terms.html$
  script: kindycal.application

- url: /edit_groups.html$
  script: kindycal.application

- url: /edit_events.html$
  script: kindycal.application

- url: /edit_roster.html$
  script: kindycal.application

- url: /edit_roster_job.html$
  script: kindycal.application

- url: /events.html$
  script: kindycal.application

- url: /twyc.html$
  script: kindycal.application

- url: /roster.html$
  script: kindycal.application

- url: /edit_twyc.html$
  script: kindycal.application

- url: /event.html$
  script: kindycal.application

- url: /edit_event.html$
  script: kindycal.application

- url: /import_data.html$
  script: kindycal.application
  
- url: /edit_public_holiday.html$
  script: kindycal.application
  
- url: /edit_maintenance_day.html$
  script: kindycal.application
  
- url: /maintenance_day.html$
  script: kindycal.application

- url: /roster_bychild.html$
  script: kindycal.application

- url: /(..*\.html)$
  static_files: \1
  upload: ..*\.html
  application_readable: true

- url: /(..*\.css)$
  static_files: \1
  upload: ..*\.css

- url: /(..*\.js)$
  static_files: \1
  upload: ..*\.js

- url: /..*
  script: kindycal.application

- url: /script/.*
  script: kindycal.application

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?jquery-ui[^/]*/tests/.*$
- ^(.*/)?jquery-ui[^/]*/demos/.*$
